data_ingestion:
  bucket_name: "mlops-krish1"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 256
  loss: binary_crossentropy
  optimizer: Adam
  metrics: ["mae", "mse"]
